# Usa a imagem oficial do Node.js
FROM node:18

WORKDIR /app

RUN rm -rf package-lock.json

# Copia os arquivos e instala dependências
COPY package.json ./

COPY package-lock.json ./

RUN yarn install
RUN yarn add bootstrap

# Copia o restante do projeto
COPY . .

# Expõe a porta do Next.js
EXPOSE 3000

# Inicia o servidor Next.js
CMD ["yarn", "dev"]
