# Usa a imagem oficial do Node.js
FROM node:18

WORKDIR /app

# Copia os arquivos e instala dependências
COPY package.json ./
COPY package-lock.json ./

RUN rm -rf package-lock.json

RUN npm install
RUN npm install yarn
RUN yarn add bootstrap

# Copia o restante do projeto
COPY . .

# Expõe a porta do Next.js
EXPOSE 3000

# Inicia o servidor Next.js
CMD ["yarn", "dev"]
